development:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: mrdavidbacon
  password: 12cpziag

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: mrdavidbacon
  password: 12cpziag  