development:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: mrdavidbacon
  password: 12cpziag

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: mrdavidbacon
  password: 12cpziag  

  production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: mrdavidbacon
  password: 12cpziag  
cucumber:
  <<: *test